@HostAddress = https://localhost:7083

GET {{HostAddress}}/api/clients?birthday=2025-02-17
Accept: application/json

###

GET {{HostAddress}}/api/clients/3/categories
Accept: application/json

###

GET {{HostAddress}}/api/orders/recent?days=25
Accept: application/json
